### ISSUE TITLE
Entrypoints Mangling

### ISSUE THREAD

**Issue by stefnotch** [wgsl-tooling-wg/wesl-spec#1]
Entrypoints and pipeline overridable constants in the final module may need to be mangled. And the locations of bindings should be changeable.

1. It should be possible to explicitly set the names and bindings. This includes overriding names and bindings from imported libraries. Without that feature, we risk producing wgsl code that cannot readily be consumed by other tools.

2. It should be possible to fall back to a predictable, or known, name for bindings. Without that feature, one has to repeatedly set the names and bindings in every root module.

3. Finally, since these names are part of the public API of a shader, it should be possible for library authors to provide "defaults" for them.

For 1., we propose that names and bindings that are re-exported in the root module will simply take those names. Example syntax
```
// blur.wesl
import assert/{violations_counter};
import ../utils/math/{USE_FAST_SQRT};

export {
  @group(4) @binding(59) violations_counter,
  math_fast_sqrt: USE_FAST_SQRT
 };
```
Limitations: 
- Each symbol can only be re-export from the root module once. `export { math_fast_sqrt: USE_FAST_SQRT, fast_math: USE_FAST_SQRT }` in the root module would be illegal.
- One can produce naming conflicts w.r.t. to a given mangling scheme. Like `export { assert_violations__counter: whatever }` would cause a naming conflict! This interacts with 2, and raises the questions whether the linker should be required to "solve" that or whether we disallow that (this making the mangling scheme observable).

For 2., the proposals currently are
- Stable and specified mangling scheme. 
  - We want there to be a "absolute path" to a function.
  - Moving something to another file is a breaking change.
- Stable and short mangling scheme.
  - `libraryname_name` is very short.
  - Different files in the same library can cause naming conflicts.
- Generating a bindings map. Lets us have multiple names per name.
  - (Cannot handle recursive modules)
  - Using the generated WGSL requires parsing additional info. This may be ok, since one can always explicitly set all names.
- Letting the mangling scheme be implementation defined. This makes swapping out linkers much harder, and makes them harder to use as a pure CLI tool.

All of these proposals do *not* fix overlapping bindings! 

For 3., re-using the syntax from 1. would be a natural option. Whenever a library exposes a binding in its root module, it gets a slightly mangled name for that symbol. e.g. `libraryname_symbol`

## Example setup
```
package.json
wesl.toml
src/
  components/
    BlurOverlay.ts
    blur.wesl
    SceneRender.ts
    scene-rendering/
      fxaa.wesl
      shader.wesl
      lights.wesl
  utils/
    math.wesl
```

And we depend on a library for assert statements inside shaders. It exposes one `assert` function, and has one binding with an atomic counter that gets incremented for each assertion violation.

**Comment by stefnotch** [comment]
Maybe we should adopt a metal-like approach where bindings and names are grouped into structs. So you'd define a struct that groups everything you need, and then re-use that every time? Then we could get away with just having 1., and not needing a mangling scheme or anything.

And if you need to change a binding/name, you define a new struct?

This may need some better "struct composition" capabilities though.

**Comment by stefnotch** [comment]
Pipeline-overridable constants and bindings are fundamentally very different.

Pipeline-overridable constants: Set during shader compilation. Purely a way of specializing a shader. Use string names.

Bindings: Must match a pipeline layout. Should be shared across different shaders. Use integers.

**Comment by mighdoll** [comment]
See also #3 for some ideas and alternatives for mangling.

**Comment by ncthbrt** [comment]
The extends keyword seems like it might address some of the issues with the option to require that entry points be included on the global namespace. This is because it instances the contents of an entire module into the current namespace

**Comment by ncthbrt** [comment]
Though maybe we could actually punt the problem to dead code elimination

**Comment by ncthbrt** [comment]
Though maybe we could actually punt the problem to dead code elimination

**Comment by mighdoll** [comment]
I’d like to argue for the idea of making host visible names like shader entry points a responsibility for apps and packages to construct, rather than exposing a mangling scheme. Under that view, each package (and the main app) should be wholly responsible for defining its public names. Subpackage entry names would not be visible to the host without the app wesl explicitly publishing them.

If a package wants to publish five versions of fragment_main, it is responsible for coming up with unique names for each. If a package wants to publish a fragment_main from a subpackage, it is responsible for re-exporting it with a unique name.

To support that, we’d need a wesl mechanism to rename and republish entry points from imported packages. We’ve discussed several schemes that could do that. But before selecting and evolving a particular rename and republish scheme, I wonder if we might find consensus on the approach. i.e. don’t expose mangling, but instead solve the entry point uniqueness problem via explicit renaming.

**Comment by stefnotch** [comment]
I'm also in favour of explicitly exposing a public API. My motivation for it is that I don't know how a mangling scheme would work with libraries (especially with the case where we have separate versions of the same library in the dependency tree).

**Comment by ncthbrt** [comment]
I'm not entirely sure what you mean by those two comments @mighdoll and @stefnotch. Could you maybe provide some code samples or expand on the comments? Because it feels like we _may_ be talking about similar things, just with a different lens

**Comment by mighdoll** [comment]
per 2024-09-19 meeting, closing in favor of #42.

Instead of exposing a user visible mangling scheme, we plan to provide a way to explicitly rename entry points from imported packages.

**Comment by stefnotch** [comment]
Sounds good 👍
