### ISSUE TITLE
Import syntax - Revise or Revisit?

### ISSUE THREAD

**Issue by mighdoll** [wgsl-tooling-wg/wesl-spec#33]
There’ve been some ideas floating around about replacing the import syntax in the current spec. #25 suggests minor revisions to address the possibility of future namespacing/submodules. But is there a more fundamental issue with the current import syntax?

**Comment by ncthbrt** [comment]
I'd personally like to revisit it. The interactions of the current spec with the features I'm most interested in seeing in WESL are not feasible. I think there are some workable alternatives being floated that could be suitable however. 

Notably this informal discussion seemed to point at a path that addressed the concerns with the most promising alternatives:

https://discord.com/channels/1275293995152703488/1275318205530898503/1285198630470549534

**Comment by mighdoll** [comment]
>  addressed the concerns 

Can you explain the concerns that motivate a change? 

Why replace file driven imports? I originally didn't use filenames in the old wgsl-linker (I had a `module` keyword, roughly akin to naga_oil's `#define_import_path`) but reviewers requested the DRY convenience and familiarity of filenames.

**Comment by ncthbrt** [comment]
Nested inline modules, generic modules, and `extend` features all require that modules can be symbolically referenced, manipulated and treated isomorphically to inline modules

**Comment by ncthbrt** [comment]
Mathis had this to say about the suggestion of centralising module declarations the wesl config file

> I like this idea a lot actually. It's one less syntax extension to wgsl. It opens the door for a lot of cool stuff too, fully controlling the imports paths in one location. I think this is my new favorite!

> like we could even construct a module tree by combining and overriding modules from different sources. This would support all kinds of imports.

> Example of a manifest like this `wesl.json` (just making stuff out here):
```json
modules: {
  bevy: { source: cargo, package: bevy, submodules: {               // mount a package declared in Cargo.toml
    pbr: { source: cargo, package: bevy_pbr }                       // override a submodule
  } },
  util: { source: manifest, path: ./src/shaders/util/wesl.json },   // mount another module tree to a path
  octree: { source: glsl, path: ./src/shaders/octree.glsl },        // importing single files, even perhaps other shader lang?
  some_lib: { source: git, url: https://github.com/some/lib.git },  // import from git
  codegen: { source: runtime, name: mod_generated_at_runtime },     // module generated at runtime and provided to the linker?
}
```

**Comment by mighdoll** [comment]
> Nested inline modules, 
Would something like #25 address this? If not, why not?

> generic modules, and `extend` features all require that modules can be symbolically referenced, manipulated and treated isomorphically to inline modules

maybe? I mean it's hard to know right now what design we or wgsl will eventually settle on for generics or interfaces or inheritance. And if the key issue is addressing import targets, wouldn't those new elements also be addressable in the same way that a wgsl fn (or an inline module) would be addressable?

**Comment by ncthbrt** [comment]
It's mostly a matter of consistency. You introduce two types of module pathing operators and classes of module to the language instead of one. It also makes modules less relocatable which means the file path becomes part of the public API. The latter means some sort of reexport design will likely become necessary.

**Comment by ncthbrt** [comment]
I'm not sure what you mean by this 
> Is it multi-level necessary for generics? A generic parameter A could be type bound to interface B, in which case accessing function c would be A.c(). (Or A::c() if we decided to switch separators)

**Comment by mighdoll** [comment]
Consensus from [2024-09-19 meeting](https://github.com/wgsl-tooling-wg/wesl-spec/blob/main/meetings/2024-09-19.md) is to revise the currently spec'd syntax.

We likely want to allow future namespaces/submodules along with virtual file paths in the same addressable hierarchy, see #25.
